import type { Metadata } from "next"
import { Analytics } from '@vercel/analytics/next'
import "./globals.css"
import Providers from "@/providers"

export const metadata: Metadata = {
  title: "ESpres App | Presupuestos",
  description: "Generated by Andreu Amano",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Providers>{children}</Providers>
        <Analytics />
      </body>
    </html>
  )
}