import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
  title: "ESpres App | Presupuestos",
  description: "Generated by Andreu Amano",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
      </body>
    </html>
  )
}
